name: Shop
version: 2.4.0
api-version: 1.17
author: [bk, CrimsonDart]
main: net.pgfmc.shop.Main
description: Implements a global market to buy and sell
commands:
  shop:
    description: Global buy/sell shop
    usage: /shop
    aliases: [ah, sh]