name: Shop
version: 4.0.0
api-version: 1.18
author: [bk, CrimsonDart]
main: net.pgfmc.shop.Main
description: Implements a global market to buy and sell
commands:
  shop:
    description: Global buy/sell shop
    usage: /<command>
    aliases: [sh]