name: Shop
version: 2.3.2
api-version: 1.17
author: bk
main: net.pgfmc.shop.Main
description: Implements a global market to buy and sell
commands:
  shop:
    description: Global buy/sell shop
    usage: /shop
    aliases: [ah, sh]